export { MainPage } from './mainPage/MainPage';
export { Galery } from './galeryPage/Galery';
export { TrustUs } from './TrustUs/TrustUs';
export { Error } from './errorPage/Error';
export { AboutUsPage } from './aboutUsPage/AboutUsPage';
export { ServicesPage } from './servicesPage/ServicesPage';
export { ShopPage } from './shopPage/ShopPage';
export { Faq } from './faq/Faq';
export { NewsPage } from './newsPage/NewsPage';
