export { AboutUsSection } from './homePage/AboutUsSection';

export { IntroductionSection } from './homePage/IntroductionSection';
export { ServicesSection } from './homePage/ServicesSection';
export { TrustUsSection } from './homePage/TrustUsSection';
export { Footer } from './footer/Footer';
export { Header } from './header/Header';
export { TrustUsMain } from './trustUsPage/TrustUsMain';
export { Preview } from './trustUsPage/Preview';
export { AboutUs } from './aboutUs/AboutUs';
export { Team } from './aboutUs/Team';
export { WhyQRush } from './aboutUs/WhyQRush';
export { NewsSection } from './homePage/NewsSection';
export { Services } from './servicPage/Services';
export { PriceList } from './servicPage/PriceList';
export { Equipment } from './servicPage/Equipment';
export { RehearsalBase } from './servicPage/RehearsalBase';
export { GaleryMain } from './galeryMain/GaleryMain';
export { ImageSection} from './galeryMain/imageSection';
export { ThirdVideoSection } from './galeryMain/ThirdVideoSection';
export {VideoSlider } from './galeryMain/VideoSlider';
export { GuitarMusicCourses } from './servicPage/GuitarMusicCourses';
export { DrumsMusicCourses } from './servicPage/DrumsMusicCourses';
export { VocalMusicCourses } from './servicPage/VocalMusicCourses';
export { ServiceOrder } from './servicPage/ServiceOrder';
export { GallerySection } from './homePage/GallerySection';
export { VideoSection } from './homePage/VideoSection';
export { FAQ } from './faqPage/FAQ';
export { Form } from './faqPage/Form';
